### ISSUE TITLE
Failed to post data to http://localhost:4318/v1/traces

### ISSUE THREAD

**Issue by xueqintang** [cisco-open/test-telemetry-generator#104]
## Description

Please provide a description of the problem.

## Expected Behavior

Please describe what you expected would happen.

## Actual Behavior

Please describe what happened instead.

## Affected Version

Please provide the version number where this issue was encountered.

## Steps to Reproduce

1. First step
1. Second step
1. etc.

## Checklist

- [ ] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ ] I have verified this does not duplicate an existing issue

When I run java -jar test-telemetry-generator-v23.7.0-fat.jar -r resource-definition.yaml -s trace-definition.yaml -t cli-target-rest.yaml, the datum can't be posted. Please see detailed logs. Could you please help to take a look? Thanks.
cat generator.log
03:18:17.495 [main] INFO  i.o.c.g.t.TelemetryGenerator - Received data generation request with metrics = (false), logs = (false), traces = (true)
03:18:17.557 [main] INFO  i.o.c.g.c.ResourceModelGenerator - 3RS8PnjRO0RNamMuAIMfD1I9kpPCDJbg: Generated 2 service resources
03:18:17.559 [main] INFO  i.o.c.g.c.ResourceModelGenerator - 3RS8PnjRO0RNamMuAIMfD1I9kpPCDJbg: Generated 8 service_instance resources
03:18:17.562 [main] INFO  i.o.c.g.c.ResourceModelGenerator - 3RS8PnjRO0RNamMuAIMfD1I9kpPCDJbg: Mapping parent -> children types: service -> [service_instance]
03:18:17.586 [main] INFO  i.o.c.g.c.ResourceModelGenerator - 3RS8PnjRO0RNamMuAIMfD1I9kpPCDJbg: Executing 4 attribute operations for service_instance types
03:18:17.597 [main] INFO  i.o.c.g.t.t.dto.Traces - 3RS8PnjRO0RNamMuAIMfD1I9kpPCDJbg: Initializing 1 trace trees
03:18:17.607 [main] INFO  i.o.c.g.t.t.TracesGenerator - 3RS8PnjRO0RNamMuAIMfD1I9kpPCDJbg: Initializing 1 trace generator threads
03:18:27.648 [pool-1-thread-1] INFO  i.o.c.g.t.t.TraceGeneratorThread - 3RS8PnjRO0RNamMuAIMfD1I9kpPCDJbg: Sending payload for: entry::group::0
03:18:27.858 [pool-1-thread-1] ERROR i.o.c.g.t.t.i.HTTPClient - Failed to post data to http://localhost:4318/v1/traces
java.io.IOException: HTTP/1.1 header parser received no bytes
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:964)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
        at io.opentelemetry.contrib.generator.telemetry.transport.implementations.HTTPClient.postBytes(HTTPClient.java:48)
        at io.opentelemetry.contrib.generator.telemetry.transport.implementations.rest.RESTPayloadHandler.postPayload(RESTPayloadHandler.java:75)
        at io.opentelemetry.contrib.generator.telemetry.traces.TraceGeneratorThread.run(TraceGeneratorThread.java:54)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by preet-dev** [comment]
Hi @xueqintang, can you kindly share the contents of your cli-target-rest.yaml? I will look at this in this week.

**Comment by xueqintang** [comment]
authMode: "none"
# Set authmode to 'basic' and uncomment username & password if you need authentication
# username: "your-username"
# password: "your-password"
restURL:
  baseURL: "http://localhost:4318"
  metricsPath: "/v1/metrics"
  logsPath: "/v1/logs"
  tracesPath: "/v1/traces"

**Comment by xueqintang** [comment]
/opt/my-test-telemetry# kubectl get svc | grep otel-collector
otel-collector                       ClusterIP   192.168.224.120   <none>        4317/TCP,4318/TCP,8888/TCP                                                  10s

**Comment by xueqintang** [comment]
It is my env issue, I will close it. Thanks.
